
pipeline {
    agent any
    
    tools {nodejs "nodejs"}

    stages {
        
        stage('SonarQube analysis') {
            environment {
                SCANNER_HOME = tool 'scanner_sonar';    
            }
            
            steps {
                
                withSonarQubeEnv('sonarqube') {
                    sh "npm install sonar-scanner"
                }
            }
        }
   
     stage("Quality Gate"){
           steps {
               script {
        timeout(time: 1, unit: 'HOURS') { 
        def qg = waitForQualityGate() 
        if (qg.status != 'OK') {
             error "Pipeline aborted due to quality gate failure: ${qg.status}"
    }
  }
           }
           }
} 
    
    }
  
  
}
