pipeline {
  agent any 
    tools {
    nodejs "nodeJs-yaya"
  }
  stages {
    stage (' listing content ') {
      steps {
        sh 'ls'
      }
    }
    stage(' cd root directory ') {
      steps {
        dir('bulletin-board-app') {
          sh 'npm install'
        }
      }
    }
      stage('build and push') {
        steps {  
          dir('bulletin-board-app') {
                       withDockerRegistry([ credentialsId: "Docker_creds", url: "https://index.docker.io/v1/" ]){
               sh 'docker build -t devopstrainingschool/bulletin-nodeJs:$BUILD_NUMBER . -f Dockerfile'
               sh 'docker push devopstrainingschool/bulletin-nodeJs:$BUILD_NUMBER'
                       }
          }
        }
        
             }
      
        
    
  
    }
  
  
  
  
  
  
}
